### ISSUE TITLE
PCA color

### ISSUE THREAD

**Issue by hanyanhanyan** [ripple-neuro/mksort#8]
Hi, I was doing PCA while when I generate a new ellipse, it doesn't change the color.
It remains the same cluster while they are actually two.

![screen shot 2017-09-21 at 7 02 52 pm](https://user-images.githubusercontent.com/32147051/30722521-aaef286a-9eff-11e7-8f47-9334d33f7945.png)

**Comment by mattkaufman** [comment]
Hi hanyanhanyan,

This is correct behavior -- you can add more than one ellipse to define a unit. If you want to define a second unit, click the third blank box (axes) along the bottom. You'll see the orange outline jump to those axes, and you can start defining a new unit.
